#!/bin/bash
yum -y install httpd mod_ssl
systemctl enable httpd
systemctl start  httpd
sed -i 's/^/#/g' /etc/httpd/conf.d/welcome.conf
echo "<html><body><h1>hi there</h1></body></html>" > /var/www/html/index.html


#CREATING A WHILE SCRIPT TO OUTPUT A SEARCH - THIS IS AN OR STATEMENT
#!/bin/bash
while IFS='' read -r line || [[ -n "$line" ]]; do 
echo "Here's the text from file: $line"
done < "$1"
