#!/bin/bash
#this is my automation for spinning up a django server

#install python
yum install python-pip

#install the version that allows for virtual instances
pip install virtualenv

#Upgrade per the system prompt
pip install --upgrade pip

#next step
yum install python36

#next step
virtualenv -p python36 django

#shell 2.75
#python --version
source django/bin/activate

#shell 3.6.6
#python --version

#putting it in our 3.6.6 version
pip install django

#django-admin --version
#starts the first project
django-admin startproject project1

#check to see if its there
#ls -l

#check to see who you are logged in as
#who

#changing the ownership of project1 and django from root to be owned by the user
chown -R koda django
chown -R koda project1

#su - koda
source /opt/django/django/bin/activate
/opt/django/project1/manage.py runserver 0.0.0.0:8000&
#enter twice
#make the firewall rule in google cloud
#then try to get to the page by deleting the s in https and add colon 8000 to the end of the line enter
#find the ALLOW command in project 1
grep -iR ALLOWED /opt/django/project1

#take the file and copy it:
#/opt/django/project1/project1/settings.p
vim /opt/django/project1/project1/settings.py

sudo -u koda  sh -c " source /opt/django/django/bin/activate && python manage.py runserver 0.0.0.0:8000&"
