#!bin/bash
#this is the code to create my personal git script account  
sudo su
yum -y install git
git clone https://github.com/dakoda17/NTI-300
git config --global user.name "dakoda17"
git config --global user.email "kodamondragon@gmail.com"
# git config --list / to check if the above commands were set
git config --global core.editor vim
#to get into the repo
cd NTI-300
